In [9]:
#Importo as bibliotecas
import pandas as pd

In [10]:
#Carrega a base de clientes
dfClientes = pd.read_csv("clientes.csv", delimiter=",")
dfClientes.head(2)

   ID_Cliente          Nome  Idade Sexo          Cidade Estado Canal_Aquisicao
0           1   Cauã Guerra     56    M       São Paulo     RS     Loja Física
1           2  Luísa Vargas     69    M  Rio de Janeiro     RJ          Online

In [11]:
#Crio uma coluna para incluir o perfil do cliente
dfClientes["Perfil"] = ""
dfClientes.head(2)

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Canal_Aquisicao,Perfil
0,1,Cauã Guerra,56,M,São Paulo,RS,Loja Física,
1,2,Luísa Vargas,69,M,Rio de Janeiro,RJ,Online,

In [12]:
#Atualizo o perfildo cliente conforme a sua idade
dfClientes.loc[(dfClientes["Idade"] >= 0) & (dfClientes["Idade"] < 23), "Perfil"] = "Jovem"
dfClientes.loc[(dfClientes["Idade"] >= 23) & (dfClientes["Idade"] <= 65), "Perfil"] = "Adulto"
dfClientes.loc[(dfClientes["Idade"] > 65), "Perfil"] = "Idoso"

dfClientes

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Canal_Aquisicao,Perfil
0,1,Cauã Guerra,56,M,São Paulo,RS,Loja Física,Adulto
1,2,Luísa Vargas,69,M,Rio de Janeiro,RJ,Online,Idoso
2,3,Larissa Monteiro,46,M,Porto Alegre,PR,Online,Adulto
3,4,Larissa Ribeiro,32,F,Porto Alegre,PR,Loja Física,Adulto
4,5,Otávio Castro,60,M,Belo Horizonte,RJ,Online,Adulto
...,...,...,...,...,...,...,...,...
995,996,Yuri Pinto,60,F,Curitiba,PR,Loja Física,Adulto
996,997,Srta. Anna Liz Mendonça,64,M,São Paulo,SP,Online,Adulto
997,998,Liz da Cunha,62,F,Curitiba,PR,Loja Física,Adulto
998,999,Maria Cecília Vasconcelos,35,M,Porto Alegre,MG,Online,Adulto
999,1000,Kamilly Teixeira,55,M,Belo Horizonte,RS,Online,Adulto

In [13]:
#Exporto os dados para um arquivo CSV
dfClientes.to_csv("dfClientes.csv", sep=",", index=False)