In [3]:
#Importo as bibliotecas
import pandas as pd

In [ ]:
#Carrego os dados dos atendimentos
dfAtendimentos = pd.read_csv("dfAtendimentos.csv", delimiter=",")
dfAtendimentos.head(10)

,ID_Atendimento,ID_Cliente,Tipo,Data,Tempo_Resposta,Nota_Satisfacao
0,1,52,Elogio,2023-10-17,14.79,2
1,2,93,Dúvida,2022-04-25,0.33,4
2,3,15,Reclamação,2022-01-26,70.74,1
3,4,72,Elogio,2024-01-30,14.35,5
4,5,61,Reclamação,2022-10-09,11.54,1
5,6,21,Dúvida,2022-09-08,89.91,1
6,7,83,Dúvida,2022-08-17,90.24,1
7,8,87,Elogio,2022-05-23,25.56,3
8,9,75,Dúvida,2024-01-25,29.98,3
9,10,75,Reclamação,2022-04-15,17.85,1

In [ ]:
#Guardo o número total de atendimentos
totalAtendimentos = dfAtendimentos.__len__()
totalAtendimentos

301

In [10]:
#Seleciono os atendimentos eficientes (tempo espera <= 60 segundos)
dfAtendEficientes = dfAtendimentos.loc[dfAtendimentos["Tempo_Resposta"] <= 60]
dfAtendEficientes

,ID_Atendimento,ID_Cliente,Tipo,Data,Tempo_Resposta,Nota_Satisfacao
0,1,52,Elogio,2023-10-17,14.79,2
1,2,93,Dúvida,2022-04-25,0.33,4
3,4,72,Elogio,2024-01-30,14.35,5
4,5,61,Reclamação,2022-10-09,11.54,1
7,8,87,Elogio,2022-05-23,25.56,3
...,...,...,...,...,...,...
295,296,32,Dúvida,2023-01-18,1.60,3
296,297,9,Reclamação,2023-03-25,12.31,2
297,298,99,Dúvida,2024-07-10,4.33,4
298,299,19,Reclamação,2023-06-14,1.96,5
300,301,80,Elogio,2022-05-04,11.67,5

In [13]:
#Guardo o número total de atendimentos eficientes
totalAtendimentosEficientes = dfAtendEficientes.__len__()
totalAtendimentosEficientes

249

In [16]:
#Calculo o percentual de atendimentos eficientes em relação ao total
percentAtenEficientes = (totalAtendimentosEficientes / totalAtendimentos) * 100
print(f'O percentual de atendimentos eficientes foi de: {percentAtenEficientes.__round__(2)} %')

O percentual de atendimentos eficientes foi de: 82.72 %

In [19]:
#Relação dos atendimentos eficientes com a satisfação
dfSatisfacaoAtendEficientes = dfAtendEficientes.groupby("Nota_Satisfacao")["ID_Atendimento"].count().reset_index()
dfSatisfacaoAtendEficientes

   Nota_Satisfacao  ID_Atendimento
0                1              45
1                2              51
2                3              55
3                4              45
4                5              53

In [ ]:
#Apesar dos atendimentos eficientes, as notas de safistação foram distribuídas de forma equivalente.
#Era esperado que tivesse uma maior concentração de notas mais altas, o que não se concretizou.